version: 2

registries:
  nuget.org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  dotnet9:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json

updates:
  - package-ecosystem: nuget
    registries: "*"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    groups:
      CommunityToolkit:
        patterns:
          - "CommunityToolkit.*"
      DotnetCore:
        patterns:
          - "System.*"
      EntityFrameworkCore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      MicrosoftExtensions:
        patterns:
          - "Microsoft.Extensions.*"
      NETTestSdk:
        patterns:
          - "Microsoft.CodeCoverage"
          - "Microsoft.NET.Test.Sdk"
      NodaTime:
        patterns:
          - "NodaTime*"
      xunit:
        patterns:
          - "xunit*"
    reviewers:
      - frankbuckley
    assignees:
      - frankbuckley

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    reviewers:
      - frankbuckley
    assignees:
      - frankbuckley

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    reviewers:
      - frankbuckley
    assignees:
      - frankbuckley
