version: 2

registries:
  nuget.org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
  - package-ecosystem: nuget
    registries: "*"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    groups:
      Azure:
        patterns:
          - "Azure.*"
          - "Microsoft.Azure.*"
      CommunityToolkit:
        patterns:
          - "CommunityToolkit.*"
      DotNet:
        patterns:
          - "System.*"
          - "Microsoft.Bcl*"
          - "Microsoft.CodeAnalysis*"
          - "Microsoft.Diagnostics*"
          - "Microsoft.AspNetCore*"
          - "Microsoft.EntityFrameworkCore*"
          - "Microsoft.Extensions.*"
          - "Microsoft.NETCore.*"
      MicrosoftIdentity:
        patterns:
          - "Microsoft.Identity*"
      NETTestSdk:
        patterns:
          - "Microsoft.CodeCoverage"
          - "Microsoft.NET.Test.Sdk"
      NodaTime:
        patterns:
          - "NodaTime*"
      Polly:
        patterns:
          - "Polly*"
      xunit:
        patterns:
          - "xunit*"
    reviewers:
      - frankbuckley
    assignees:
      - frankbuckley

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    reviewers:
      - frankbuckley
    assignees:
      - frankbuckley

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    reviewers:
      - frankbuckley
    assignees:
      - frankbuckley
