version: 2

registries:
  nuget.org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
  - package-ecosystem: nuget
    registries: "*"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    groups:
      Azure:
        patterns:
          - "Azure.*"
          - "Microsoft.Azure.*"
      CommunityToolkit:
        patterns:
          - "CommunityToolkit.*"
      DotNetRuntime:
        patterns:
          - "System.*"
          - "Microsoft.AspNetCore*"
          - "Microsoft.Bcl*"
          - "Microsoft.Diagnostics*"
          - "Microsoft.Extensions.*"
          - "Microsoft.NETCore.*"
        exclude-patterns:
          - "Microsoft.Extensions.AI*"
      EntityFrameworkCore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      Identity:
        patterns:
          - "Microsoft.Identity*"
      MicrosoftTesting:
        patterns:
          - "Microsoft.Testing.*"
      NodaTime:
        patterns:
          - "NodaTime*"
      Polly:
        patterns:
          - "Polly*"
      Roslyn:
        patterns:
          - "Microsoft.CodeAnalysis*"
      SQLitePCLRaw:
        patterns:
          - "SQLitePCLRaw.*"
      Testing:
        patterns:
          - "AwesomeAssertions"
          - "Moq"
          - "Verify.*"
          - "coverlet.*"
      xunit:
        patterns:
          - "xunit*"
    assignees:
      - frankbuckley

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    groups:
      Jupyter:
        patterns:
          - "ipython*"
          - "jupyter*"
          - "jupyterlab*"
          - "notebook"
      DataScience:
        patterns:
          - "numpy"
          - "pandas"
          - "matplotlib"
      MachineLearning:
        patterns:
          - "torch*"
          - "stanza"
          - "sentence-transformers"
          - "einops"
          - "hf-xet"
    assignees:
      - frankbuckley

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    assignees:
      - frankbuckley
