coverage:
  precision: 1
  round: down
  range: "75...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        paths:
          - "src"
          - "gen"
ignore:
  - "test"
  - "benchmarks"
