// Copyright (c) Down Syndrome Education International and Contributors. All Rights Reserved.
// Down Syndrome Education International and Contributors licence this file to you under the MIT license.

using System.Text.Json.Serialization;

namespace DSE.Open.Numerics.Serialization;

[JsonSourceGenerationOptions(
    UseStringEnumConverter = true,
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DictionaryKeyPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    WriteIndented = false)]
[JsonSerializable(typeof(DataSet))]
[JsonSerializable(typeof(ReadOnlyDataSet))]
[JsonSerializable(typeof(DataFrame))]
[JsonSerializable(typeof(ReadOnlyDataFrame))]
[JsonSerializable(typeof(Vector))]
[JsonSerializable(typeof(Vector<char>))]
[JsonSerializable(typeof(Vector<string>))]
[JsonSerializable(typeof(Vector<Guid>))]
[JsonSerializable(typeof(Vector<DateTime>))]
[JsonSerializable(typeof(Vector<DateTimeOffset>))]
[JsonSerializable(typeof(Vector<byte>))]
[JsonSerializable(typeof(Vector<sbyte>))]
[JsonSerializable(typeof(Vector<short>))]
[JsonSerializable(typeof(Vector<ushort>))]
[JsonSerializable(typeof(Vector<int>))]
[JsonSerializable(typeof(Vector<uint>))]
[JsonSerializable(typeof(Vector<long>))]
[JsonSerializable(typeof(Vector<ulong>))]
[JsonSerializable(typeof(Vector<Int128>))]
[JsonSerializable(typeof(Vector<UInt128>))]
[JsonSerializable(typeof(Vector<Half>))]
[JsonSerializable(typeof(Vector<float>))]
[JsonSerializable(typeof(Vector<double>))]
[JsonSerializable(typeof(Vector<decimal>))]
[JsonSerializable(typeof(Vector<DateTime64>))]
[JsonSerializable(typeof(ReadOnlyVector<char>))]
[JsonSerializable(typeof(ReadOnlyVector<string>))]
[JsonSerializable(typeof(ReadOnlyVector<Guid>))]
[JsonSerializable(typeof(ReadOnlyVector<DateTime>))]
[JsonSerializable(typeof(ReadOnlyVector<DateTimeOffset>))]
[JsonSerializable(typeof(ReadOnlyVector<byte>))]
[JsonSerializable(typeof(ReadOnlyVector<sbyte>))]
[JsonSerializable(typeof(ReadOnlyVector<short>))]
[JsonSerializable(typeof(ReadOnlyVector<ushort>))]
[JsonSerializable(typeof(ReadOnlyVector<int>))]
[JsonSerializable(typeof(ReadOnlyVector<uint>))]
[JsonSerializable(typeof(ReadOnlyVector<long>))]
[JsonSerializable(typeof(ReadOnlyVector<ulong>))]
[JsonSerializable(typeof(ReadOnlyVector<Int128>))]
[JsonSerializable(typeof(ReadOnlyVector<UInt128>))]
[JsonSerializable(typeof(ReadOnlyVector<Half>))]
[JsonSerializable(typeof(ReadOnlyVector<float>))]
[JsonSerializable(typeof(ReadOnlyVector<double>))]
[JsonSerializable(typeof(ReadOnlyVector<decimal>))]
[JsonSerializable(typeof(ReadOnlyVector<DateTime64>))]
[JsonSerializable(typeof(DataPoint<byte>))]
[JsonSerializable(typeof(DataPoint<sbyte>))]
[JsonSerializable(typeof(DataPoint<short>))]
[JsonSerializable(typeof(DataPoint<ushort>))]
[JsonSerializable(typeof(DataPoint<int>))]
[JsonSerializable(typeof(DataPoint<uint>))]
[JsonSerializable(typeof(DataPoint<long>))]
[JsonSerializable(typeof(DataPoint<ulong>))]
[JsonSerializable(typeof(DataPoint<Int128>))]
[JsonSerializable(typeof(DataPoint<UInt128>))]
[JsonSerializable(typeof(DataPoint<Half>))]
[JsonSerializable(typeof(DataPoint<float>))]
[JsonSerializable(typeof(DataPoint<double>))]
[JsonSerializable(typeof(DataPoint<decimal>))]
[JsonSerializable(typeof(DataPoint<DateTime64>))]
[JsonSerializable(typeof(DataPoint3D<byte>))]
[JsonSerializable(typeof(DataPoint3D<sbyte>))]
[JsonSerializable(typeof(DataPoint3D<short>))]
[JsonSerializable(typeof(DataPoint3D<ushort>))]
[JsonSerializable(typeof(DataPoint3D<int>))]
[JsonSerializable(typeof(DataPoint3D<uint>))]
[JsonSerializable(typeof(DataPoint3D<long>))]
[JsonSerializable(typeof(DataPoint3D<ulong>))]
[JsonSerializable(typeof(DataPoint3D<Int128>))]
[JsonSerializable(typeof(DataPoint3D<UInt128>))]
[JsonSerializable(typeof(DataPoint3D<Half>))]
[JsonSerializable(typeof(DataPoint3D<float>))]
[JsonSerializable(typeof(DataPoint3D<double>))]
[JsonSerializable(typeof(DataPoint3D<decimal>))]
[JsonSerializable(typeof(DataPoint3D<DateTime64>))]
public sealed partial class NumericsJsonSerializationContext : JsonSerializerContext;
