// Copyright (c) Down Syndrome Education International and Contributors. All Rights Reserved.
// Down Syndrome Education International and Contributors licence this file to you under the MIT license.

using System.Text.Json.Serialization;

namespace DSE.Open.Numerics.Serialization;

[JsonSourceGenerationOptions(
    UseStringEnumConverter = true,
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    DictionaryKeyPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    WriteIndented = false)]
[JsonSerializable(typeof(DataSet))]
[JsonSerializable(typeof(ReadOnlyDataSet))]
[JsonSerializable(typeof(DataFrame))]
[JsonSerializable(typeof(ReadOnlyDataFrame))]
[JsonSerializable(typeof(Series))]
[JsonSerializable(typeof(Series<char>))]
[JsonSerializable(typeof(Series<string>))]
[JsonSerializable(typeof(Series<Guid>))]
[JsonSerializable(typeof(Series<DateTime>))]
[JsonSerializable(typeof(Series<DateTimeOffset>))]
[JsonSerializable(typeof(Series<byte>))]
[JsonSerializable(typeof(Series<sbyte>))]
[JsonSerializable(typeof(Series<short>))]
[JsonSerializable(typeof(Series<ushort>))]
[JsonSerializable(typeof(Series<int>))]
[JsonSerializable(typeof(Series<uint>))]
[JsonSerializable(typeof(Series<long>))]
[JsonSerializable(typeof(Series<ulong>))]
[JsonSerializable(typeof(Series<Int128>))]
[JsonSerializable(typeof(Series<UInt128>))]
[JsonSerializable(typeof(Series<Half>))]
[JsonSerializable(typeof(Series<float>))]
[JsonSerializable(typeof(Series<double>))]
[JsonSerializable(typeof(Series<decimal>))]
[JsonSerializable(typeof(Series<DateTime64>))]
[JsonSerializable(typeof(ReadOnlySeries<char>))]
[JsonSerializable(typeof(ReadOnlySeries<string>))]
[JsonSerializable(typeof(ReadOnlySeries<Guid>))]
[JsonSerializable(typeof(ReadOnlySeries<DateTime>))]
[JsonSerializable(typeof(ReadOnlySeries<DateTimeOffset>))]
[JsonSerializable(typeof(ReadOnlySeries<byte>))]
[JsonSerializable(typeof(ReadOnlySeries<sbyte>))]
[JsonSerializable(typeof(ReadOnlySeries<short>))]
[JsonSerializable(typeof(ReadOnlySeries<ushort>))]
[JsonSerializable(typeof(ReadOnlySeries<int>))]
[JsonSerializable(typeof(ReadOnlySeries<uint>))]
[JsonSerializable(typeof(ReadOnlySeries<long>))]
[JsonSerializable(typeof(ReadOnlySeries<ulong>))]
[JsonSerializable(typeof(ReadOnlySeries<Int128>))]
[JsonSerializable(typeof(ReadOnlySeries<UInt128>))]
[JsonSerializable(typeof(ReadOnlySeries<Half>))]
[JsonSerializable(typeof(ReadOnlySeries<float>))]
[JsonSerializable(typeof(ReadOnlySeries<double>))]
[JsonSerializable(typeof(ReadOnlySeries<decimal>))]
[JsonSerializable(typeof(ReadOnlySeries<DateTime64>))]
[JsonSerializable(typeof(DataPoint<byte>))]
[JsonSerializable(typeof(DataPoint<sbyte>))]
[JsonSerializable(typeof(DataPoint<short>))]
[JsonSerializable(typeof(DataPoint<ushort>))]
[JsonSerializable(typeof(DataPoint<int>))]
[JsonSerializable(typeof(DataPoint<uint>))]
[JsonSerializable(typeof(DataPoint<long>))]
[JsonSerializable(typeof(DataPoint<ulong>))]
[JsonSerializable(typeof(DataPoint<Int128>))]
[JsonSerializable(typeof(DataPoint<UInt128>))]
[JsonSerializable(typeof(DataPoint<Half>))]
[JsonSerializable(typeof(DataPoint<float>))]
[JsonSerializable(typeof(DataPoint<double>))]
[JsonSerializable(typeof(DataPoint<decimal>))]
[JsonSerializable(typeof(DataPoint<DateTime64>))]
[JsonSerializable(typeof(DataPoint3D<byte>))]
[JsonSerializable(typeof(DataPoint3D<sbyte>))]
[JsonSerializable(typeof(DataPoint3D<short>))]
[JsonSerializable(typeof(DataPoint3D<ushort>))]
[JsonSerializable(typeof(DataPoint3D<int>))]
[JsonSerializable(typeof(DataPoint3D<uint>))]
[JsonSerializable(typeof(DataPoint3D<long>))]
[JsonSerializable(typeof(DataPoint3D<ulong>))]
[JsonSerializable(typeof(DataPoint3D<Int128>))]
[JsonSerializable(typeof(DataPoint3D<UInt128>))]
[JsonSerializable(typeof(DataPoint3D<Half>))]
[JsonSerializable(typeof(DataPoint3D<float>))]
[JsonSerializable(typeof(DataPoint3D<double>))]
[JsonSerializable(typeof(DataPoint3D<decimal>))]
[JsonSerializable(typeof(DataPoint3D<DateTime64>))]
public sealed partial class NumericsJsonSerializationContext : JsonSerializerContext;
