// Copyright (c) Down Syndrome Education International and Contributors. All Rights Reserved.
// Down Syndrome Education International and Contributors licence this file to you under the MIT license.

namespace DSE.Open.Speech;

public static class PhonemeLabel
{
    public static bool TryGetLabel(PhonemeLabelScheme scheme, Phoneme phoneme, out string label)
    {
        if (s_Labels.TryGetValue(scheme, out var labels) && labels.TryGetValue(phoneme, out label!))
        {
            return true;
        }

        label = default!;
        return false;
    }

    private static readonly Dictionary<PhonemeLabelScheme, Dictionary<Phoneme, string>> s_Labels = new()
    {
        {
            PhonemeLabelScheme.Default, new Dictionary<Phoneme, string>()
            {
                { Phonemes.English.a, "a" },
                { Phonemes.English.ah, "ah" },
                { Phonemes.English.air, "air" },
                { Phonemes.English.ar, "ar" },
                { Phonemes.English.aw, "aw" },
                { Phonemes.English.ay, "ay" },
                { Phonemes.English.b, "b" },
                { Phonemes.English.ch, "ch" },
                { Phonemes.English.d, "d" },
                { Phonemes.English.dh, "dh" },
                { Phonemes.English.e, "e" },
                { Phonemes.English.ee, "ee" },
                { Phonemes.English.eer, "eer" },
                { Phonemes.English.er, "er" },
                { Phonemes.English.f, "f" },
                { Phonemes.English.g, "g" },
                { Phonemes.English.h, "h" },
                { Phonemes.English.hw, "hw" },
                { Phonemes.English.i, "i" },
                { Phonemes.English.igh, "igh" },
                { Phonemes.English.j, "j" },
                { Phonemes.English.k, "k" },
                { Phonemes.English.k͟h, "kh" },
                { Phonemes.English.l, "l" },
                { Phonemes.English.m, "m" },
                { Phonemes.English.n, "n" },
                { Phonemes.English.ng, "ng" },
                { Phonemes.English.o, "o" },
                { Phonemes.English.oh, "oh" },
                { Phonemes.English.oo, "oo" },
                { Phonemes.English.oor, "oor" },
                { Phonemes.English.or, "or" },
                { Phonemes.English.ow, "ow" },
                { Phonemes.English.oy, "oy" },
                { Phonemes.English.p, "p" },
                { Phonemes.English.r, "r" },
                { Phonemes.English.s, "s" },
                { Phonemes.English.sh, "sh" },
                { Phonemes.English.t, "t" },
                { Phonemes.English.th, "th" },
                { Phonemes.English.u, "u" },
                { Phonemes.English.uh, "uh" },
                { Phonemes.English.ur, "ur" },
                { Phonemes.English.uu, "uu" },
                { Phonemes.English.v, "v" },
                { Phonemes.English.w, "w" },
                { Phonemes.English.y, "y" },
                { Phonemes.English.yoo, "yoo" },
                { Phonemes.English.z, "z" },
                { Phonemes.English.zh, "zh" },
            }
        },
        {
            PhonemeLabelScheme.OED, new Dictionary<Phoneme, string>()
            {
                { Phonemes.English.a, "a" },
                { Phonemes.English.ah, "ah" },
                { Phonemes.English.air, "air" },
                { Phonemes.English.ar, "ar" },
                { Phonemes.English.aw, "aw" },
                { Phonemes.English.ay, "ay" },
                { Phonemes.English.b, "b" },
                { Phonemes.English.ch, "ch" },
                { Phonemes.English.d, "d" },
                { Phonemes.English.dh, "dh" },
                { Phonemes.English.e, "e" },
                { Phonemes.English.ee, "ee" },
                { Phonemes.English.eer, "eer" },
                { Phonemes.English.er, "ur" },      // only difference from default
                { Phonemes.English.f, "f" },
                { Phonemes.English.g, "g" },
                { Phonemes.English.h, "h" },
                { Phonemes.English.hw, "hw" },
                { Phonemes.English.i, "i" },
                { Phonemes.English.igh, "igh" },
                { Phonemes.English.j, "j" },
                { Phonemes.English.k, "k" },
                { Phonemes.English.k͟h, "kh" },
                { Phonemes.English.l, "l" },
                { Phonemes.English.m, "m" },
                { Phonemes.English.n, "n" },
                { Phonemes.English.ng, "ng" },
                { Phonemes.English.o, "o" },
                { Phonemes.English.oh, "oh" },
                { Phonemes.English.oo, "oo" },
                { Phonemes.English.oor, "oor" },
                { Phonemes.English.or, "or" },
                { Phonemes.English.ow, "ow" },
                { Phonemes.English.oy, "oy" },
                { Phonemes.English.p, "p" },
                { Phonemes.English.r, "r" },
                { Phonemes.English.s, "s" },
                { Phonemes.English.sh, "sh" },
                { Phonemes.English.t, "t" },
                { Phonemes.English.th, "th" },
                { Phonemes.English.u, "u" },
                { Phonemes.English.uh, "uh" },
                { Phonemes.English.ur, "ur" },
                { Phonemes.English.uu, "uu" },
                { Phonemes.English.v, "v" },
                { Phonemes.English.w, "w" },
                { Phonemes.English.y, "y" },
                { Phonemes.English.yoo, "yoo" },
                { Phonemes.English.z, "z" },
                { Phonemes.English.zh, "zh" },
            }
        },
        {
            PhonemeLabelScheme.BBC, new Dictionary<Phoneme, string>()
            {
                { Phonemes.English.a, "a" },
                { Phonemes.English.ah, "aa" },
                { Phonemes.English.air, "air" },
                { Phonemes.English.ar, "ar" },
                { Phonemes.English.aw, "aw" },
                { Phonemes.English.ay, "ay" },
                { Phonemes.English.b, "b" },
                { Phonemes.English.ch, "ch" },
                { Phonemes.English.d, "d" },
                { Phonemes.English.dh, "dh" },
                { Phonemes.English.e, "e" },
                { Phonemes.English.ee, "ee" },
                { Phonemes.English.eer, "eer" },
                { Phonemes.English.er, "uhr" },
                { Phonemes.English.f, "f" },
                { Phonemes.English.g, "g" },
                { Phonemes.English.h, "h" },
                { Phonemes.English.hw, "hw" },
                { Phonemes.English.i, "i" },
                { Phonemes.English.igh, "igh" },
                { Phonemes.English.j, "j" },
                { Phonemes.English.k, "k" },
                { Phonemes.English.k͟h, "kh" },
                { Phonemes.English.l, "l" },
                { Phonemes.English.m, "m" },
                { Phonemes.English.n, "n" },
                { Phonemes.English.ng, "ng" },
                { Phonemes.English.o, "o" },
                { Phonemes.English.oh, "oh" },
                { Phonemes.English.oo, "oo" },
                { Phonemes.English.oor, "oor" },
                { Phonemes.English.or, "or" },
                { Phonemes.English.ow, "ow" },
                { Phonemes.English.oy, "oy" },
                { Phonemes.English.p, "p" },
                { Phonemes.English.r, "r" },
                { Phonemes.English.s, "s" },
                { Phonemes.English.sh, "sh" },
                { Phonemes.English.t, "t" },
                { Phonemes.English.th, "th" },
                { Phonemes.English.u, "u" },
                { Phonemes.English.uh, "uh" },
                { Phonemes.English.ur, "ur" },
                { Phonemes.English.uu, "uu" },
                { Phonemes.English.v, "v" },
                { Phonemes.English.w, "w" },
                { Phonemes.English.y, "y" },
                { Phonemes.English.yoo, "yoo" },
                { Phonemes.English.z, "z" },
                { Phonemes.English.zh, "zh" },
            }
        },
        {
            PhonemeLabelScheme.SeeAndLearnV2, new Dictionary<Phoneme, string>()
            {
                { Phonemes.English.a, "a" },
                { Phonemes.English.air, "air" },
                { Phonemes.English.ar, "ar" },
                // { Phonemes.English.aw, "aw" },
                { Phonemes.English.ay, "ai" },
                { Phonemes.English.b, "b" },
                { Phonemes.English.ch, "ch" },
                { Phonemes.English.d, "d" },
                { Phonemes.English.dh, "TH" },
                { Phonemes.English.e, "e" },
                { Phonemes.English.ee, "ee" },
                { Phonemes.English.eer, "ear" },
                // { Phonemes.English.er, "uhr" },
                { Phonemes.English.f, "f" },
                { Phonemes.English.g, "g" },
                { Phonemes.English.h, "h" },
                // { Phonemes.English.hw, "hw" },
                { Phonemes.English.i, "i" },
                { Phonemes.English.igh, "igh" },
                { Phonemes.English.j, "j" },
                { Phonemes.English.k, "k" },
                // { Phonemes.English.k͟h, "kh" },
                { Phonemes.English.l, "l" },
                { Phonemes.English.m, "m" },
                { Phonemes.English.n, "n" },
                { Phonemes.English.ng, "ng" },
                { Phonemes.English.o, "o" },
                { Phonemes.English.oh, "oa" },
                { Phonemes.English.oo, "oo" },
                { Phonemes.English.oor, "ure" },
                { Phonemes.English.or, "or" },
                { Phonemes.English.ow, "ow" },
                { Phonemes.English.oy, "oi" },
                { Phonemes.English.p, "p" },
                { Phonemes.English.r, "r" },
                { Phonemes.English.s, "s" },
                { Phonemes.English.sh, "sh" },
                { Phonemes.English.t, "t" },
                { Phonemes.English.th, "th" },
                { Phonemes.English.u, "u" },
                { Phonemes.English.uh, "uh" },
                { Phonemes.English.ur, "ur" },
                { Phonemes.English.uu, "OO" },
                { Phonemes.English.v, "v" },
                { Phonemes.English.w, "w" },
                { Phonemes.English.y, "y" },
                //{ Phonemes.English.yoo, "yoo" },
                { Phonemes.English.z, "z" },
                { Phonemes.English.zh, "zh" },
            }
        },
    };
}
