name: PR Build and Test

on: [pull_request]

jobs:
  build_test:
    name: Build and Test

    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]
        configuration: [Debug, Release]

    runs-on: ${{ matrix.os }}

    timeout-minutes: 45
    
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # avoid shallow clone

      - name: Cache Stanza downloads
        id: cache-stanza-downloads
        uses: actions/cache@v4
        env:
          cache-name: cache-stanza-downloads
          stanza-version: 1.11.0
        with:
          path: ~/stanza_resources
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.stanza-version }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.stanza-version }}

      - name: Set Python version
        uses: actions/setup-python@v6
        with:
          python-version: "3.13.7"
          cache: "pip"

      - name: Configure Python environment
        run: ./eng/scripts/init_python.ps1

      - name: Set .NET SDK version
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
          dotnet-version: | 
            8.0.x
            9.0.x
            10.0.x

      - name: Set Versions
        id: nbgv
        uses: dotnet/nbgv@master
        with:
          setCommonVars: true
          setAllVars: true

      - name: Initialise versions.props
        run: ./eng/scripts/versions.ps1
        shell: pwsh

      - name: Diagnostics
        run: "Get-ChildItem Env:"
        shell: pwsh

      - name: Restore
        run: dotnet restore ./DSE.Open.slnx

      - name: Build DSE.Open.Values.Generators
        run: dotnet build ./gen/DSE.Open.Values.Generators/DSE.Open.Values.Generators.csproj --configuration ${{ matrix.configuration }}

      - name: Build
        run: dotnet build ./DSE.Open.slnx --no-restore --configuration ${{ matrix.configuration }}

      - name: Run Tests
        uses: dseinternational/open-dotnet/.github/actions/dotnet-test@actions-0.9
        with:
          target: ./test
          configuration: ${{ matrix.configuration }}
        env:
          STANZA_NLP: en
          PYTHON3_HOME: ${{ env.Python3_ROOT_DIR }}

      # - name: Generate coverage report
      #   if: matrix.configuration == 'Debug'
      #   uses: danielpalme/ReportGenerator-GitHub-Action@5
      #   with:
      #     reports: "${{ github.workspace }}/coverage/report.cobertura.xml"
      #     targetdir: "${{ github.workspace }}/coverage/coveragereport"
      #     reporttypes: "MarkdownSummaryGithub"

      # - name: Upload coverage report into summary
      #   if: matrix.configuration == 'Debug'
      #   shell: bash
      #   run: cat ${{ github.workspace }}/coverage/coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

      # - name: Archive code coverage results
      #   if: matrix.configuration == 'Debug'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code-coverage-report
      #     path: ${{ github.workspace }}/coverage

      # - name: Upload coverage reports to Codecov
      #   if: matrix.configuration == 'Debug'
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: ${{ github.workspace }}/coverage
