name: PR Build and Test

on: [pull_request]

jobs:
  build_test:
    name: Build and Test

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone

      - name: Cache Stanza downloads
        id: cache-stanza-downloads
        uses: actions/cache@v4
        env:
          cache-name: cache-stanza-downloads
          stanza-version: 1.8.2
        with:
          path: ~/stanza_resources
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.stanza-version }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.stanza-version }}

      - name: Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
          cache: "pip"

      - name: Install Python packages
        run: |
          pip3 install torch>=2.3.1 --index-url https://download.pytorch.org/whl/cpu
          python -m pip install -r ./requirements.txt --progress-bar off --verbose

      - name: Initialize Python environment
        run: python ./eng/scripts/init_ci.py

      - name: Set .NET SDK version
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Set Versions
        id: nbgv
        uses: dotnet/nbgv@master
        with:
          setCommonVars: true
          setAllVars: true

      - name: Initialise versions.props
        run: ./eng/scripts/versions.ps1
        shell: pwsh

      - name: Diagnostics
        run: "Get-ChildItem Env:"
        shell: pwsh

      - name: Restore
        run: dotnet restore ./DSE.Open.sln

      - name: Build DSE.Open.Values.Generators
        run: dotnet build ./gen/DSE.Open.Values.Generators/DSE.Open.Values.Generators.csproj --configuration ${{ matrix.configuration }}

      - name: Build
        run: dotnet build ./DSE.Open.sln --configuration ${{ matrix.configuration }}

      - name: Test
        run: |
          dotnet test ./DSE.Open.sln `
            --configuration ${{ matrix.configuration }} `
            --collect:"XPlat Code Coverage" `
            --verbosity normal
        shell: pwsh
        env:
          STANZA_NLP: en

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
